### ISSUE TITLE
Help says `index.js` instead of `arcgis`

### ISSUE THREAD

**Issue by gavinr** [Esri/arcgis-js-cli#1]
## Description
Minor issue - when I view the help, it says `index.js` everywhere it should say the command name (`arcgis`).

## Expected Behavior
Help text should look like what's in the `README` (and not have `index.js`)

## Actual Behavior
Help text says `index.js` everywhere it should say `arcgis`:
![image](https://user-images.githubusercontent.com/209355/40091731-06df060c-587f-11e8-94a7-47ee066154e0.png)

## Steps to Reproduce

1. `npm install -g @arcgis/cli`
2. `arcgis --help`

## Your Environment
* Version used: `@arcgis/cli@4.7.2`
* Browser Name and version: `n/a`
* Operating System and version (desktop or mobile): `Windows 10`
* Link to your project if available: `n/a`

**Comment by odoe** [comment]
That's weird, just tried on Win10 at home and see the same thing. CLI still works though. This may be an issue with `yargs` on Windows, I'll look into it when I get a chance.

**Comment by odoe** [comment]
I tried again with the latest yargs, evenm updated all other deps and same thing.

When I get a chance, I'll see if I can create a minimal repro case for yargs and submit an issue.

Thanks!

**Comment by gavinr** [comment]
@odoe I think I found the issue: https://github.com/yargs/yargs/issues/1010 and related fix: https://github.com/yargs/yargs/pull/1143

**Comment by odoe** [comment]
Awesome @gavinr!

I updated this in [4.9.2](https://github.com/Esri/arcgis-js-cli/releases/tag/4.9.2), hopefully this addresses the issue for impacted users.

**Comment by gavinr** [comment]
I updated to v4.9.2 and it works as expected now. Thanks @odoe!
