### ISSUE TITLE
How to Create Calcite App ?

### ISSUE THREAD

**Issue by mayur9785** [Esri/arcgis-js-cli#102]
## Description
Hi,

I installed arcgis-cli as 

`npm install -g @arcgis/cli`

I am running this command 

`arcgis create jsapi-app-calcite -t calcite`

above command from here : https://odoe.net/blog/new-arcgis-cli-template-apps/

Couldn't generate the calcite App

I am getting message

**Invalid values:
Argument: type, Given: "calcite", Choices: "jsapi", "rollup"**

![image](https://user-images.githubusercontent.com/6058868/107507295-69e58e00-6bb0-11eb-89dc-5a0e98cf8739.png)

## Expected Behavior

The command should generate the app like this => https://jsapi-app-calcite-414.surge.sh/

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: 
npm version  : 7.5.3
node version : 14.10.1
* Browser Name and version:
* Operating System and version (desktop or mobile): 
Windows 10 Version 1903
* Link to your project if available:

**Comment by odoe** [comment]
There is no longer an option to create calcite apps with the CLI. This might be added back in the future, I'll update here if that changes.

**Comment by mayur9785** [comment]
Thank you @odoe !!

Looking for configurable template the same as Map Viewer Beta and Calcite.

**Comment by mayur9785** [comment]
@odoe,  if Calcite app template created before and available, could you please share old repository URL ?

**Comment by odoe** [comment]
You can find it here
https://github.com/Esri/arcgis-js-cli/tree/4.16.0

**Comment by mayur9785** [comment]
@odoe , Thank you 👍
