### ISSUE TITLE
Fonts not getting loaded from assets

### ISSUE THREAD

**Issue by rangasatishkumar** [Esri/arcgis-js-cli#104]
Fonts not getting loaded from assets, due to which esri-icons are not rendering properly.

## Description

Due to missing fonts, esri-icons are not rendering properly. Please refer to the enclosed screenshots.

## Expected Behavior

esri-icons should render properly for widgets

## Actual Behavior

![map](https://user-images.githubusercontent.com/17163418/119612932-129dbd80-be2f-11eb-90d6-426e292c7ec0.png)

![console](https://user-images.githubusercontent.com/17163418/119613125-41b42f00-be2f-11eb-8a03-506ad4cfa7b8.png)

## Steps to Reproduce

1. npm run build
2. deploy the dist folder (I have renamed dist to jsapp) to a web server
3. launch the web application in browser. (My application URL is http://localhost:8080/jsapp/)
4.

## Your Environment

* Version used: 4.19.0
* Browser Name and version: Chrome Version 91.0.4472.77 (Official Build) (32-bit)
* Operating System and version (desktop or mobile): Microsoft Windows 10 Pro
* Link to your project if available:

**Comment by odoe** [comment]
Since your app isn't running at the root of the server, you need to update the esriConfig.assetsPath as described here.
https://developers.arcgis.com/javascript/latest/api-reference/esri-config.html#assetsPath

```js
config.assetsPath = "./jsapp/assets";
```

**Comment by rangasatishkumar** [comment]
When used **assetsPath** as below, along with the fonts related errors, getting few other errors. Please refer to the enclosed screenshots.

`config.assetsPath = "./jsapp/assets";`

![assetsPath](https://user-images.githubusercontent.com/17163418/119755214-3830d280-bed4-11eb-9da1-3eda91caeaa9.png)

![console](https://user-images.githubusercontent.com/17163418/119755278-55fe3780-bed4-11eb-8c0f-062b1f471bd0.png)

**Comment by odoe** [comment]
That update was a community contribution, so I'm not very familiar with it. You can try removing it or playing with the paths used. Alternatively, you can remove all sass builds from the project and just let the assets get loaded from the CDN.

I might update the templates for 4.20 to remove the sass builds from the project to simplify things and let users add sass configuration themselves.

**Comment by rangasatishkumar** [comment]
Possible to provide some sample code with the workarounds? Thank you.

**Comment by qQsss777** [comment]
Hi, I encountered the same issue. I modified the webpack configuration.

I create a variable at the begining of the file :
```
const folder = 'dist'
```
then in the module rules array :
```
            {
              loader: 'resolve-url-loader',
              options: {
                sourceMap: true,
                debug: mode === 'development',
                join: (_rul_uri, _rul_base) => {
                  // args must be included
                  return (assetPath, absolutePath) => {
                    // ArcGISPlugin copies assets and cannot be resolved when using api sass
                    // replace relative path with absolute path in `dist` so files can be found for resolving
                    return absolutePath.includes('@arcgis/core')
                      ? assetPath.replace('../', `./${folder}/assets/esri/themes/`)
                      : assetPath;
                  };
                },
              },
            },
```
