### ISSUE TITLE
Widget command creates the widget in a tmp folder

### ISSUE THREAD

**Issue by MichalisM** [Esri/arcgis-js-cli#105]
## Description

We have a jsapi app. We load the app in the vscode. From the terminal of vscode (but also from the command prompt) we call e.g. C:\repos\myAPP\ arcgis widget myAwesomeWidget. 
## Expected Behavior

A folder widget is created, if it doesn't exist with a subfolder myAwesomeWidget and inside the viewmodel and the styles folder
## Actual Behavior

A tmp folder is created, with a subfolder myAwesomeWidget and a second subfolder WidgetName which seems to be the template of creating a widget. This is not reproducible in 4.18.0

## Steps to Reproduce

1. arcgis create myApp
2. arcgis widget myAwesomeWidget
3.
4.

## Context

Just creating a widget :-)

## Your Environment

* Version used: 4.19.0
* Browser Name and version: NA
* Operating System and version (desktop or mobile): Windows 10 Enterprise
* Link to your project if available: NA

**Comment by rangasatishkumar** [comment]
This issue still persist in version 4.21.0

**Comment by ranga-tolapi** [comment]
Issue persist in version 4.22.1

![image](https://user-images.githubusercontent.com/17163418/150627017-63229a81-6447-43ec-8391-6e004d88662f.png)
