### ISSUE TITLE
Create a new theme - failed

### ISSUE THREAD

**Issue by ranga-tolapi** [Esri/arcgis-js-cli#106]
Creation of a new theme is failing

## Description

![image](https://user-images.githubusercontent.com/17163418/123397909-8d482d00-d5d5-11eb-831c-b7eeab99a589.png)

## Actual Behavior

```
NestedError: Cannot copy `preview/`: the file doesn't exist
    at C:\Users\rt89280\AppData\Roaming\npm\node_modules\@arcgis\cli\node_modules\cpy\index.js:96:10
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  nested: undefined,
  name: 'CpyError'
```

## Steps to Reproduce

1. arcgis styles create my-custom-theme
2.
3.
4.

## Your Environment

* Version used: 4.19.0
* Browser Name and version: N.A.
* Operating System and version (desktop or mobile): Microsoft Windows 10 Pro (laptop)
* Link to your project if available:

**Comment by mikael-mansson** [comment]
Would highly appreciate this update @jcfranco

**Comment by instantgis** [comment]
I needed this in a hurry! So I debugged through the code and fond a work around/ugly hack that may work for others too...
Copy folder preview here and its contents (index.html)  to .arcgis-js-cli-styles where the base styles are copied by the tool in the target project.
You will still have a problem with import @esri/calcite-components/dist/calcite/calcite in _core.scss - not found!
npm install --save @esri/calcite-components
Then copy @esri/calcite-components from node_modules to .arcgis-js-cli-styles/base
Now you can preview and play

**Comment by instantgis** [comment]
Its failing to copy preview here in src/commands/styles/scaffold.ts 

	await cpy('preview/', buildPath(`${workspacePath}/<preview>`, dirs), {
		cwd: buildPath(`<dirname>/../../`, dirs),
	});

No idea why. Because of the trailing / on cpy ?

**Comment by rangasatishkumar** [comment]
I have found a workaround 😊

Copy **preview** folder
from %AppData%\npm\node_modules\@arcgis\cli\dist\
to %AppData%\npm\node_modules\@arcgis\cli\

**Comment by jcfranco** [comment]
I finally had some time and submitted a PR for this. I'm sorry it took so long to get to it.

Thank you all for sharing your workarounds and additional error info, it was most helpful.

**Comment by jcfranco** [comment]
Installed. This should be available in the next release. cc @odoe

**Comment by claesjs** [comment]
@jcfranco Do you have an ETA on the next release?

**Comment by odoe** [comment]
i'll do a patch update later today

**Comment by ranga-tolapi** [comment]
Issue persist with version 4.22.1

![image](https://user-images.githubusercontent.com/17163418/150626680-293b28bf-ca04-4c9e-9230-82a96a16f079.png)

**Comment by odoe** [comment]
Thanks, we'll need to some debugging on Windows, thanks.

**Comment by claesjs** [comment]
I'm getting the same error on Mac, arcgis version 4.22.1.

<img width="1195" alt="Screenshot 2022-01-25 at 15 48 13" src="https://user-images.githubusercontent.com/12586651/150999253-36ee8d25-1567-44ce-b9a6-328a7e267008.png">

The problem seems to be that `arcgis-js-api` is located on the same level as `@arcgis`, i.e. in node_modules. If I read the log output correctly is seems like `@arcgis` looks for `arcgis-js-api` in its own node_modules directory.

**Comment by sfabijanski** [comment]
I'm on Linux (Fedora 35), with version 4.23.0 of the CLI tool. Using Node v16.14.2. I just experienced the missing preview copy error mentioned above.

`arcgis styles create my-theme -e`
![image](https://user-images.githubusercontent.com/1973336/191549302-b282a5ee-4c29-4715-b89c-d260e199f1ae.png)

**Comment by Tlepel** [comment]
I tried to find why the second fault , the failed import `@import "@esri/calcite-components/dist/calcite/calcite";` didn't work, and I found out that changing it to `@import "@esri/calcite-components/dist/calcite/calcite.css";` actually solved that part of the problem.

**Comment by andygup** [comment]
Closing this issue in preparation for deprecation of the library.
