### ISSUE TITLE
Upgrade to 4.21.0

### ISSUE THREAD

**Issue by rangasatishkumar** [Esri/arcgis-js-cli#107]
Would like to check, any plans to upgrade the cli to 4.20.0?

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project if available:

**Comment by bsnider** [comment]
Also curious... @odoe

**Comment by odoe** [comment]
Been swamped recently, sorry. Will get to it as soon as I can. Might wait for 4.21, it's fairly close at this point.

**Comment by bsnider** [comment]
great, thanks @odoe!

**Comment by odoe** [comment]
There is a new branch ready for when 4.21 goes live.
https://github.com/Esri/arcgis-js-cli/tree/4.21

Some notes:

* Replace rollup template with vite. Vite still uses rollup, just faster.
* Simplify the webpack template. Had some feedback about how the template relied on extending Widget, which isn't a common use case.

**Comment by bsnider** [comment]
@odoe Thank you!
