### ISSUE TITLE
watchUtils.whenOnce not getting triggered from custom widget

### ISSUE THREAD

**Issue by ranga-tolapi** [Esri/arcgis-js-cli#109]
watchUtils.whenOnce not getting triggered from a custom widget

## Description

**What I did:**
Created a new application using the command "arcgis create jsapi-app-4210"
Created a new widget using the command "arcgis widget HelloWorld"
	- Got errors, refer to the enclosure CreateWidget_Error.log.
	- To fix, moved the widget related files to respective directories manually.
Executed the command "npm start"
	Got errors, refer to the enclosure AdditionalLoader_Error.log.
	To fix, added below properties to "compilerOptions" section of tsconfig.json
	 - "jsx": "react",
	- "jsxFactory": "tsx"
Executed the command "npm start"
	- Entered ArcGIS Online credentials
"whenOnce" of watchUtils initiated in "init" method of HelloWorldViewModel.ts was not triggered
	- View scale never printed to console.

## Expected Behavior

View scale should print to console from HelloWorld widget.

## Actual Behavior

View scale not printed to console.

## Steps to Reproduce

1. Download and extract the enclosure jsapi-app-4210.zip
2. Run "npm install"
3. Run "npm start"
4. Monitor browser console for View.scale (it won't print)

## Your Environment

* Version used: 4.21.0
* Browser Name and version: Google Chrome Version 93.0.4577.82 (Official Build) (32-bit)
* Operating System and version (desktop or mobile): Microsoft Windows 10 Pro
* Link to your project if available:
[jsapi-app-4210.zip](https://github.com/Esri/arcgis-js-cli/files/7231236/jsapi-app-4210.zip)
[AdditionalLoader_Error.log](https://github.com/Esri/arcgis-js-cli/files/7231240/AdditionalLoader_Error.log)
[CreateWidget_Error.log](https://github.com/Esri/arcgis-js-cli/files/7231241/CreateWidget_Error.log)

**Comment by odoe** [comment]
I'm either going to deprecate the custom widget command or make it standalone. It's tsconfig is not compatible with current template projects, as it needs to down to es5, which I do not want to do for the default templates. I meant to add the log warning in this release.

**Comment by ranga-tolapi** [comment]
This is working with the below change in tsconfig.json

Change "target": "esnext" to "target": "es2021".
