### ISSUE TITLE
Module not found for client-side FeatureLayer

### ISSUE THREAD

**Issue by ReneU** [Esri/arcgis-js-cli#11]
Creating a FeatureLayer with client-side graphics causes a runtime error because of a missing worker module.

## Description
When creating an app with the CLI and adding a simple FeatureLayer with client-side graphics (like [here](https://developers.arcgis.com/javascript/latest/sample-code/layers-featurelayer-collection/index.html)), the layer cannot be created and errors are logged to the console.

## Expected Behavior
The layer is added without errors.

## Actual Behavior
`
Error: Module not found: esri/layers/graphics/sources/support/MemorySourceWorker
    at findModule (index.c27875b3b81d7914f7ad.js:278)
    at contextRequire (index.c27875b3b81d7914f7ad.js:299)
    at result (index.c27875b3b81d7914f7ad.js:221)
    at eval (workers.js:25)
`

## Possible Fix
It looks like a webworker (MemorySourceWorker) module cannot be resolved.

## Steps to Reproduce
1. clone [https://github.com/ReneU/client-side-featurelayer](https://github.com/ReneU/client-side-featurelayer)
2. `npm install`
3. `npm start`

## Context
I was trying to use the sample provided [here](https://developers.arcgis.com/javascript/latest/sample-code/layers-featurelayer-collection/index.html) in my [app](https://github.com/ReneU/client-side-featurelayer). The only changes to the app template are in `https://github.com/ReneU/client-side-featurelayer/blob/master/src/widgets/App.tsx`

## Your Environment
* Version used: 4.9.2
* Browser Name and version: Google Chrome  70.0.3538.102
* Operating System and version (desktop or mobile): Windows 10
* Link to your project if available: https://github.com/ReneU/client-side-featurelayer

**Comment by odoe** [comment]
This will be fixed in the `4.10.0` release when the `4.10` version of the JSAPI is released in the next couple of weeks.

**Comment by ReneU** [comment]
Perfect, thank you!

**Comment by odoe** [comment]
Fixed in latest release! https://github.com/Esri/arcgis-js-cli/releases/tag/4.10.0
