### ISSUE TITLE
Could not locate symbol object properly, it might be misplaced

### ISSUE THREAD

**Issue by ZhaoJiwu** [Esri/arcgis-js-cli#115]
## Description
in the 3D view environment of the CGCS2000 coordinate system, after I add the elevation layer, the graphics layer cannot render the point symbol style, while the polyline and polygon render completely normally. When I don't add an elevation layer, points, polyline , and polygon are all fine. Similarly, if a similar situation does not occur in the 3D view environment of the wgs84 coordinate system, this is a very strange phenomenon, can you help me solve it?

## Steps to Reproduce
1. Set the spherical coordinate system to CGCS2000.
2. Load a DEM layer.
3. Draw a point symbol

## Your Environment

* Version used:4.22.1
* Browser Name and version: Microsoft Edge  98.0.1108.43
* Operating System and version (desktop or mobile): Windows 10

**Comment by odoe** [comment]
This doesn't seem to be an issue with the cli. You would probably get better results posting the question on the Esri community
https://community.esri.com/t5/arcgis-api-for-javascript-questions/bd-p/arcgis-api-for-javascript-questions
