### ISSUE TITLE
Any plans to update this library?

### ISSUE THREAD

**Issue by ranga-tolapi** [Esri/arcgis-js-cli#116]
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project if available:

**Comment by odoe** [comment]
Debating. With the ease of use of other cli tooling like vite, cra, ng-cli, very little need for the template apps in this repo.

* The custom widget might be useful still.
* Custom styles and ExB widget are most useful pieces.

For 4.25, we'll make some updates to the readme and narrow down use.
