### ISSUE TITLE
v4.25 - npm ERR! code FETCH_ERROR

### ISSUE THREAD

**Issue by ranga-tolapi** [Esri/arcgis-js-cli#117]
**arcgis create jsapi-app** throwing an error. Please refer to the screenshot.

![image](https://user-images.githubusercontent.com/17163418/201478057-ce8f392f-3d8d-4b21-8cde-c3ada8b74705.png)

## Steps to Reproduce

1. arcgis create jsapi-app
2.
3.
4.

## Your Environment

* Version used: 4.25
* Browser Name and version: Chrome Version 107.0.5304.107 (Official Build) (32-bit)
* Operating System and version (desktop or mobile): Windows 10 Pro
* Link to your project if available:

**Comment by odoe** [comment]
Looks like this error is coming from the typescript eslint packages. What version of node/npm are you using? I can't repro on mac w/ node 16.17.0 and npm 8.15.0

It could have been a hiccup in npm at the time of install, but beyond that, I don't have a fix, since it's. not in the cli or the api.

**Comment by ranga-tolapi** [comment]
After I upgraded the node version, it was successful. Thank you @odoe 

![image](https://user-images.githubusercontent.com/17163418/201828610-9d873989-42fb-4925-9aaa-96a62e802287.png)
