### ISSUE TITLE
Widget not got created

### ISSUE THREAD

**Issue by ranga-tolapi** [Esri/arcgis-js-cli#118]
Even though widget creation command was successful. Widget corresponding files were not found in the corresponding location.

![image](https://user-images.githubusercontent.com/17163418/201856037-8a70b191-5260-4dab-af67-43f1fa08191d.png)

## Steps to Reproduce

1. arcgis create jsapi-app
2. cd jsapi-app
3. arcgis widget HelloWorld
4.

## Your Environment

* Version used: 4.25.0
* Browser Name and version: Chrome Version 107.0.5304.107 (Official Build) (32-bit)
* Operating System and version (desktop or mobile): Windows 10 Pro
* Link to your project if available:

**Comment by odoe** [comment]
This should be fixed in 4.25.1
