### ISSUE TITLE
Build error : ENOENT: no such file or directory, open '/Users/x/Workspace/app/node_modules/dojo/dojo.js'

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-js-cli#12]
## Description

I faced an issue on a project that started from this CLI : I recreated the package-lock.json file and then I could not build my application any more. Build throws:
`Error: ENOENT: no such file or directory, open '/Users/x/Workspace/app/node_modules/dojo/dojo.js'`

Indeed, no dojo folder is installed in node_modules.  Taking a look at the package-lock.json file which have been updated, all the dojo dependencies from arcgis-js-api have moved from requires to dependencies:

![image](https://user-images.githubusercontent.com/11556423/49683992-6ab0a000-facd-11e8-957e-e8a599bfa0f9.png)

I can reproduce this issue on the application generated by the CLI.  

## Expected Behavior
`rm -rf node_modules && rm package-lock.json && npm install && npm run build && rm -rf node_modules && npm install && npm run build` should work

## Actual Behavior
Throws error:
`Error: ENOENT: no such file or directory, open '/Users/x/Workspace/app/node_modules/dojo/dojo.js'`

## Possible Fix

I noticed that in the application generated by `arcgis init`, package-lock.json file is not commited as it is in .[gitignore](https://github.com/Esri/arcgis-js-cli/blob/da25f686fe25661b39b512f114625aa1d1f1f7b7/templates/app/gitignore#L12). Isn't that file supposed to be commited ? 
It actually solved my issue because I was building the application on gitlab runner and it would not build because of my package-lock.json that I had recreated. Removing it fixed it but is there another solution because npm mention that this file should be commited ?

## Steps to Reproduce

1. arcgis init
2. rm -rf node_modules
3. npm install
4. npm run build

## Context

I would like to be able to build the application with package-lock.json in source control.

## Your Environment

* Version used: npm 6.4.1, node v8.9.1, @arcgis/cli: 4.9.2
* Browser Name and version: 
* Operating System and version (desktop or mobile): MacOS Mojave
* Link to your project if available:

**Comment by odoe** [comment]
This happens sometimes. I can add the package-lock.json as a commit in the template app for the next release.

**Comment by odoe** [comment]
This should happen less now. It's a bit intermittent, but I think it's ok now.

**Comment by Biboba** [comment]
Hi @odoe,
I trie again and on my side it is systematic. If I commit the package-lock.json, npm packages are not properly installed and web app is not built by GitLab runner.

`rm -rf node_modules && rm package-lock.json && npm install && npm run build && rm -rf node_modules && npm install && npm run build` fails all the time on my side.
