### ISSUE TITLE
"useDefineForClassFields" in tsconfig.json should be "false"

### ISSUE THREAD

**Issue by ranga-tolapi** [Esri/arcgis-js-cli#120]
Hi @odoe, for your attention...

As per [Recenter custom widget with Vite](https://github.com/Esri/jsapi-resources/tree/main/esm-samples/jsapi-custom-widget#known-issues)... When using Vite 3, ["useDefineForClassFields": false](https://www.typescriptlang.org/tsconfig#useDefineForClassFields) needs to be set in tsconfig.json. The ArcGIS JS API requires this setting for the widget's property binding to work.

## Description

arcgis-js-cli scaffolded applications currently have ["useDefineForClassFields": true](https://www.typescriptlang.org/tsconfig#useDefineForClassFields).

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: 4.25.1
* Browser Name and version: Version 107.0.5304.123 (Official Build) (32-bit)
* Operating System and version (desktop or mobile): Windows 10 Pro
* Link to your project if available:

**Comment by odoe** [comment]
I may just remove the flag entirely, depending on if this functionality is deprecated.

**Comment by andygup** [comment]
Closing the issue and in preparation for deprecating the library. Plans are in the works for an eventual replacement.
