### ISSUE TITLE
Question: Future plans for this utility

### ISSUE THREAD

**Issue by Kasea** [Esri/arcgis-js-cli#121]
Curious about the future plans for this cli utility. In its current state it's basically useless unless you do a lot of manual patches and additional installs.

While I could make it work for a one time setup, I would rather not include `.arcgis-js-cli-styles` in my repo and have it be created seperately. To achieve that in the current state would require more than just a simple install script.

**Comment by odoe** [comment]
We are looking at updating the custom styles function of the cli. Application scaffolding will be removed as there are better tools today for this purpose.

**Comment by Kasea** [comment]
@Ebbed was thinking about the tool as a whole, personally just interested in style creation though.

@odoe any idea about timeline? curious if I should write a postinstall script or not. If it isn't _too far_ into the future I will just put it on hold

**Comment by andygup** [comment]
Plans are in the works for an eventual replacement. In the interim, closing this issue issue in preparation for deprecation of the library.
