### ISSUE TITLE
widget create command for exb creates folder named widget not name supplied

### ISSUE THREAD

**Issue by VeretaxDemo** [Esri/arcgis-js-cli#122]
## Description
For reference this was run in GitBash on Windows 10.

From git bash I ran the following command:

`arcgis widget my-sample exb`

(I also tried MySample, and with and without double quotes)

## Expected Behavior
I had expected it to create a folder with the name my-sample  in the folder I was in which was the widgets folder under the project application directory.   In that folder, I expected there to be a small scaffold for starting a widget. 

There is a scaffold, but the folder was not named "my-sample", "mysample", or "MySample", it was named "widget".

This surprsied me, because Why have a name parameter to pass in, (and I tried -n and --name as well) if it seems to completely ignore it? The manifest.json has the name as &lt;%name%&gt; and so I am left wondering, whether this feature flag was ever actually implemented?  I know I can just rename it, but for a beginner this could be problematic.  I looked at other issues, and I know there are questions of where the command is run from that may impact what it does.

For example:

- From project application root
- From your-extensions
- From client
- From a Widgets folder

For me I would have expected this to create a folder with the widget name, as place to start where I was, unless I added a 'destionation' path of some kind.  I have also seen suggestion that some of this capability might be deprecating, and that other tools are better, but I didn't see a suggested reference of what other tools those would be in the docs in Github here.

## Actual Behavior
$ arcgis widget my-sample exb
Creating Widget Template
root C:\Users\%UserName%\AppData\Roaming\npm\node_modules\@arcgis\cli/templates/exb/widget
dest C:\code\%projectfolder%\widgets\client
target C:\code\%projectfolder%\widgets\widget
 widget : C:\code\%projectfolder%\widgets\widget\config.json

 widget : C:\code\%projectfolder%\widgets\widget\config.ts

 widget : C:\code\%projectfolder%\widgets\widget\default.ts

 widget : C:\code\%projectfolder%\widgets\widget\icon.svg

 widget : C:\code\%projectfolder%\widgets\widget\manifest.json

 widget : C:\code\%projectfolder%\widgets\widget\README.md

 widget : C:\code\%projectfolder%\widgets\widget\setting.tsx

 widget : C:\code\%projectfolder%\widgets\widget\widget.test.tsx

 widget : C:\code\%projectfolder%\widgets\widget\widget.tsx

 widget : C:\code\%projectfolder%\widgets\widget\zh-cn.js

## Steps to Reproduce

1.  Open Git Bash
2. Cd to the directory you want to create the widget in (for me it was under C:\code\%projectfolder%\widgets
3. run one these command variatons

- `arcgis widget my-sample exb`
- `arcgis widget -n my-sample exb
- `arcgis widget --name my-sample exb`
- `arcgis widget my-sample  -t exb`
- `arcgis widget my-sample -type exb`

(you can subsistute PascalCase/CamelCase/DashedCase for the widget name)

## Context
In my case I am trying to learn Experience builder for the first time, but had previous experience with dot net cli as well as react cli.   

## Your Environment

* Version used: 
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project if available:

**Comment by andygup** [comment]
Thanks @VeretaxDemo. Closing this issue in preparation for deprecating the library.  Plans are in the works for an eventual replacement.
