### ISSUE TITLE
New widget styles are not getting effected

### ISSUE THREAD

**Issue by rangasatishkumar** [Esri/arcgis-js-cli#13]
## Description

Style file (scss) that's got created under "styles" folder for a widget is not getting applied. Do we need to load the style file manually somewhere?

## Expected Behavior

Style file should be applied on to the widget in runtime

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: 4.9.3
* Browser Name and version: Mozilla Firefox 63.0.3 (64-bit)
* Operating System and version (desktop or mobile): Laptop, Microsoft Windows 10 Pro
* Link to your project if available:

**Comment by odoe** [comment]
Yes, you can import it in the `main.scss` file. Like `@import "../widgets/MyWidget/styles/MyWidget";`

I can try injecting it into the `main.scss` when using `arcgis create widget my-widget`, it just gets a little a tricky if the user has modified it in some way.

**Comment by rangasatishkumar** [comment]
Noted, thank you.
