### ISSUE TITLE
Support for ArcGIS API for JavaScript v4.10

### ISSUE THREAD

**Issue by rangasatishkumar** [Esri/arcgis-js-cli#15]
Support for ArcGIS API for JavaScript v4.10

## Description

Any plans to upgrade to ArcGIS API for JavaScript v4.10?

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project if available:

**Comment by odoe** [comment]
done in latest release!
https://github.com/Esri/arcgis-js-cli/releases/tag/4.10.0
