### ISSUE TITLE
arcgis-api (dojo/dijit/dgrid) not listed as dependencies in package.json

### ISSUE THREAD

**Issue by davewilton** [Esri/arcgis-js-cli#18]
## Description
Created an app, cleaned node modules. Re-install. Dojo/dijit/dojo-util and dgrid are all missing. I believe this causes the following error

![image](https://user-images.githubusercontent.com/2278405/52841883-8da4a380-3151-11e9-8c60-1a48d27cf875.png)

## Expected Behavior
The app still builds after cleaning and reinstalling dependencies. 

## Actual Behavior
Error see image.

## Possible Fix

I added  "arcgis-js-api": "^4.10.1" as a dependency manually 

## Steps to Reproduce

1. Create an app using the cli
2. Delete node_modules
3. npm install
4. App will no longer build due to missing dojo files

## Your Environment

* Version used: 4.10
* Browser Name and version: Chrome 72
* Operating System and version (desktop or mobile): Windows 10. Node
* Link to your project if available:

**Comment by davewilton** [comment]
I have checked this in the latest version and its still an issue, jsapi is not added as a dependency of the project. Result is sharing the project with a team without the node_modules causes the above error. Sorry I can't see where to fix this

![image](https://user-images.githubusercontent.com/2278405/57746808-35604c00-7716-11e9-8106-d6e64f323a80.png)

**Comment by odoe** [comment]
I'm going to do some more testing on this one. If we do this, I think I need to have the JSAPI as a `peerDependencies` of the webpack plugin, but I was hoping to keep the plugin and the api installs linked as a single install. I'll carve out some time to test this scenario.

This does occasionally happen to me too on Mac and second npm install will fix it.
