### ISSUE TITLE
render() method being triggered so many times and so many occasions

### ISSUE THREAD

**Issue by rangasatishkumar** [Esri/arcgis-js-cli#19]
`render()` method of a custom widget being triggered so many times unnecessarily (I think).

## Description

It's been observed that `render()` method of a custom widget is being triggered so many times. As per my knowledge `render()` method should invoke only in 3 occasions as listed below.

1) Whenever a property decorated with `@renderable()` is modified
2) An explicit call of a method `renderNow()`
3) An explicit call of a method `scheduleRender()`

## Expected Behavior
`render()` method should be invoked only for the occasions listed in above description.

## Actual Behavior

`render()` method is being called whenever clicking on the widget and after that on the map.
`render()` method is being called whenever switching windows forth and back (alt + tab) then moving cursor on the map.

## Possible Fix

Do not know

## Steps to Reproduce

1. Create a new project using cli (`arcgis create TestRender`)
2. Create a new widget using cli (`arcgis widget SampleWidget`)
3. In **SampleWidget.tsx** file, comment `@renderable` decorator at line number 21 & 27
4. In `render()` method add `console.log("Called render()");` at line number 31
5. Instantiate `SampleWidget` in `AppViewModel.ts` at line numbers 46 & 47
6. Run the project using `npm start`
7. While application loading in the browser, open developer tools
8. Click on the widget and map continuously and watch the console section in developer tools

**SampleWidget.tsx**
![image](https://user-images.githubusercontent.com/17163418/53400311-8a7aa480-39e8-11e9-9913-9a93f0c85662.png)

**AppViewModel.ts**
![image](https://user-images.githubusercontent.com/17163418/53401037-01fd0380-39ea-11e9-8536-9ce5ddc98ff8.png)

**Console of Browser Developer Tools**
![image](https://user-images.githubusercontent.com/17163418/53400602-2c01f600-39e9-11e9-9903-4062a3976c67.png)

## Context

I think render() method is being called unnecessarily so many times which can overload the application.

## Your Environment

* Version used: 4.9.3
* Browser Name and version: Chrome 72.0.3626.119 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Microsoft Windows 10 Pro (desktop)
* Link to your project if available:

**Comment by odoe** [comment]
This is expected. If the returned vnode is not updated, then no changes occur in the app. You do not want to be doing anything that would impact performance in a `render()` method, that should happen in a view model.

**Comment by rangasatishkumar** [comment]
Noted, thank you.
