### ISSUE TITLE
Error when using await on promise

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-js-cli#21]
## Description

When trying to use await on esri js promise (eg: await map.load()), I have a typescript warning:
"TS1308: 'await' expression is only allowed within an async function."

and compilation fails:
"Module parse failed: The keyword 'yield' is reserved (38:16)
You may need an appropriate loader to handle this file type."

Any idea ? Thanks !

## Expected Behavior
I expected await to work on esri js api Promise.

## Actual Behavior

Typescript compilation failed.

## Your Environment

* Version used: 4.10
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project if available:

**Comment by jgravois** [comment]
hey @Biboba!

are you saying that your TypeScript doesn't compile when you use `await` _within_ an async function or that you were expecting the JSAPI to provide some ✨ that would allow you to use `await` _outside_ an async function.

if the latter, i don't know how that would work.

**Comment by Biboba** [comment]
Thanks for the reply @jgravois !

Apologize, I had no experience with async/await and was giving a try to my project based on arcgis-js-cli after having a look at the following sample:
https://ycabon.github.io/2019-devsummit-plenary/1_client-side-queries.html
And I did not notice the async at the very beginning !
I thought it was as simple as adding await before methods returning promises.
Indeed, adding async to my function solve my function !

I think I should stop for today :confused: !
