### ISSUE TITLE
"Zoom to" of popup just centers not zoom

### ISSUE THREAD

**Issue by rangasatishkumar** [Esri/arcgis-js-cli#22]
"Zoom to" of popup just centers not zoom

## Description

view.popup default action i.e. "zoom-to" do not zoom just centering
![image](https://user-images.githubusercontent.com/17163418/54442291-58ec3200-4779-11e9-905e-687c2583f2cd.png)

## Expected Behavior

Click on "Zoom To" of popup should Center And Zoom

## Actual Behavior

Click on "Zoom To" of popup just Center not Zoom

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: 4.9.3
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Desktop
* Link to your project if available:

**Comment by odoe** [comment]
This isn't an issue with the cli, but related to the JSAPI. I also do not see this behavior with the latest version.

You can try updating your project to use the latest version of the `@arcgis/webpack-plugin` by updating it in your `package.json`.

`"@arcgis/webpack-plugin": "~4.10.0"`

**Comment by rangasatishkumar** [comment]
Noted, thank you.
