### ISSUE TITLE
How can I import dojo/i18n files ?

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-js-cli#24]
## Description

Working on app built with this CLI, I am trying to customize a widget view you provide, but nls files are not imported.
```js
import * as i18nCommon from "dojo/i18n!esri/nls/common";
import * as i18n from "dojo/i18n!esri/widgets/Editor/nls/Editor";
```
Is there any setting that should be modified so that the import work ?

Thanks !

## Expected Behavior

nls files should be imported.

## Actual Behavior

nls files are not imported so there is no text on the widget

## Steps to Reproduce

1. Copy a widget view provided [here](https://github.com/Esri/arcgis-js-api/tree/4master/widgets) 
2. Instantiate the widget using the local view of the widget in your project

## Your Environment

* Version used: 4.11
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project if available:

**Comment by Biboba** [comment]
Solved.
Just need to switch to require:
```js
import i18nCommon = require("dojo/i18n!esri/nls/common");
import i18n = require("dojo/i18n!esri/widgets/Editor/nls/Editor");
```

**Comment by jgravois** [comment]
thanks for taking the time to document what you figured out @Biboba!
