### ISSUE TITLE
print default widget lost format

### ISSUE THREAD

**Issue by mnavidad** [Esri/arcgis-js-cli#26]
## Description

used the arcgis cli to create app
## Expected Behavior

the print widget should display with proper formatting
![image](https://user-images.githubusercontent.com/5179550/57059446-6efb7680-6c83-11e9-8c9d-ae0e28d697d2.png)

## Actual Behavior

 it does not diplay with the proper css formatting
![image](https://user-images.githubusercontent.com/5179550/57059380-15934780-6c83-11e9-926c-75d7410af05d.png)

## Steps to Reproduce

1. added a the default print widget from agol 
2. to the AppViewModel.ts file
3. const print = new Print({
    view: this.view,
    printServiceUrl:"https://utility.arcgisonline.com/arcgis/rest/services/Utilities/PrintingTools/GPServer/Export%20Web%20Map%20Task"
  })
4. this.view.ui.add(printExpand, "top-right");

## Context

jut trying to add the print widget from agol
## Your Environment

* Version used: 4.11
* Browser Name and version:  73.0.3683.103 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Windows 10
* Link to your project if available:

**Comment by mnavidad** [comment]
it was missing main.css 

add the css to  index.ejs problem solved 
![image](https://user-images.githubusercontent.com/5179550/57079324-172e3100-6cbe-11e9-9939-c90274cefcc8.png)

**Comment by odoe** [comment]
What you want to do is in the sass for your application, is to include the Print sass into your project by setting the variable to true.

```sass
$include_Print: true;
```

https://github.com/Esri/arcgis-js-cli/blob/master/templates/basic/app/src/css/main.scss#L21

This method of filtering out sass on a per-project basis will keep the css to a minimum for your apps.

**Comment by mnavidad** [comment]
Thank you so much!!!!
