### ISSUE TITLE
Missing source maps

### ISSUE THREAD

**Issue by davewilton** [Esri/arcgis-js-cli#27]
## Description
Source maps are missing in chrome:
![image](https://user-images.githubusercontent.com/2278405/57743586-042d4f00-7709-11e9-896e-e32345adc164.png)

I also worry that users new to webpack won't know where to look for the source. Is it worth adding this to the readme?

## Expected Behavior
Source maps are used for TS code

## Actual Behavior
No source maps

## Possible Fix
Webpack config needs updating

## Steps to Reproduce
Create new project and attempt to debug

## Your Environment
Chrome latest on windows 10

**Comment by odoe** [comment]
Thanks!

I'll do an updated release later this week, appreciate it!

**Comment by davewilton** [comment]
@odoe do you want me to add a readme section around debugging? I wonder it adding steps to debug with VS code might also be useful.

**Comment by odoe** [comment]
The more help the better, would appreciate it!

**Comment by sevenninety** [comment]
source-maps look to be missing from the React template. The following section is missing in webpack.config.js but included in the basic template:

if (arg.mode === "development") {
        config.devtool = "source-map";
}

**Comment by odoe** [comment]
This should be fixed in the latest release.
