### ISSUE TITLE
tdd development

### ISSUE THREAD

**Issue by davewilton** [Esri/arcgis-js-cli#31]
## Description
Having out of the box tests is great. But they are really slow to launch and do not lend themselves to test driven development. Is there a reason that the server starts and then shuts down rather than watching for changes? I haven't looked into this I wanted to check with you before I did.

**Comment by odoe** [comment]
Most of the template apps are using jest now, so you could add an npm script like this.

```
"test:watch": "jest --watchAll"
```

And that can watch for test changes. I'm a little hesitant to add it to all the templates, because I've had so-so luck running dev servers and test watchers concurrently in the same command.
