### ISSUE TITLE
app creation partially fails; node-sass version under macOS

### ISSUE THREAD

**Issue by wiringa** [Esri/arcgis-js-cli#33]
## Description
App creation only partially succeeds due to lack of node-sass; webpack failures result from lack of node-sass in the project.

This appears if there is no binding available for the version of node-sass in `package.json` and compilation of node-sass fails, which I'm experiencing and seems related to [this GeoNet post](https://community.esri.com/thread/231587-js-api-410-error-custom-build-dojo-nodejs), where node-sass version referenced also did not have a binding available.

## Expected Behavior
Scaffold a new app with all dependencies installed.

## Actual Behavior
New app created without all dependencies; mixed reporting of success (something went wrong, but was installed).

## Possible Fix
Bump node-sass to ~4.12.0 in `templates/basic/app/package.json`. Consider sticking with versions of node-sass that have bindings available in future releases.

## Steps to Reproduce

1. `npm install -g @arcgis/cli`
2. `arcgis create example`
3. `cd example`
4. `npm start`

Step 2 above includes these three lines at end of output:
```
Running npm install
✖ Oops, something went wrong...
Done! Your ArcGIS JSAPI application has been installed!
```

Step 4 errors out and includes a couple of `Error: Cannot find module 'node-sass'` messages.

Running `npm install` in the new app directory has output that includes:
```
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.11.0/darwin-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.11.0/darwin-x64-72_binding.node":

HTTP error 404 Not Found
```

## Context
Create an app.

## Your Environment
* macOS 10.14.4
* node v12.4.0
* @arcgis/cli: 4.11.1

**Comment by odoe** [comment]
This should be fixed in latest updates of the template apps now, thanks!
