### ISSUE TITLE
ESRI JS Promise never resolves in intern tests

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-js-cli#35]
Test that include an ESRI JS Promise never resolves in intern tests and test fails with the following error:
```
TimeoutError: Timeout reached on chrome 75.0.3770.100 on Mac OS X - widgets/App/AppViewModel - should resolve ESRI Promise#
      @ node_modules/intern/browser/remote.js:99:10665  
```
## Description

ESRI JS Promise never resolves but "classic" one does resolve and test succeed.
For example, in any test suite add the following sample:

```js
import esriRequest from "esri/request";

test("should resolve ESRI Promise", async () => {
      return esriRequest('https://services.arcgisonline.com/arcgis/rest/services?f=json', {
        responseType: "json"
      }).then(function(response:any){
        assert.equal(response.data.currentVersion, '10.6');
      });
});

 test("should resolve a Promise", () => {
      function solvePromise(resolve:any, reject:any) {
        const req = new XMLHttpRequest();
        req.onreadystatechange = function(event) {
            if (this.readyState === XMLHttpRequest.DONE) {
                if (this.status === 200) {
                    resolve(this.responseText);
                }
            }
        };
        req.open('GET', 'https://services.arcgisonline.com/arcgis/rest/services?f=json', true);
        req.send(null);
      }

      var promise = new Promise(solvePromise);
      return promise.then(function(value:string) {
        assert.equal(JSON.parse(value).currentVersion, '10.6');
      });
});
```

Test 'should resolve ESRI Promise' never resolve and fails with a timeout error but 'should resolve a Promise' does resolve and test succeeds.

## Expected Behavior

ESRI JS Promise should resolve in intern tests and test should be successful.

## Actual Behavior

ESRI JS Promise never resolves in intern test and test fails.

## Possible Fix

No idea

## Steps to Reproduce

1. Include ```import esriRequest from "esri/request";``` in  any test suite
2. Copy paste the 2 tests described above
3. Run ```npm test```

## Context

I cannot test any function that returns an ESRI JS Promise

## Your Environment

* Version used: 4.11.0
* Browser Name and version:  Chrome Version 75.0.3770.100

Any idea @odoe ? Thanks !

**Comment by Biboba** [comment]
I believe ESRI JS API leverage Dojo deferred so I tried with Dojo deferred and it does resolve as well so the test is successful:

```js
import Deferred from "dojo/Deferred";

test("should resolve a Deferred", () => {

    function solvePromise() {
      const deferred = new Deferred();
      const req = new XMLHttpRequest();

      req.onreadystatechange = function(event) {
          if (this.readyState === XMLHttpRequest.DONE) {
              if (this.status === 200) {
                deferred.resolve(this.responseText);
              }
          }
      };
      req.open('GET', 'https://services.arcgisonline.com/arcgis/rest/services?f=json', true);
      req.send(null);
      return deferred.promise;
    }
    
    var process = solvePromise();

    return process.then(function(value:string) {
      assert.equal(JSON.parse(value).currentVersion, '10.6');
    });
  });

```

**Comment by Biboba** [comment]
Basically, it is pretty much the same issue as https://github.com/Esri/arcgis-js-cli/issues/23.
Scripts are not loaded because of 404 error and thus promise never resolves.

Trying to debug it, I think the issue comes from the fact that dynamic import in 'arcgis-js-api/request.js':
```js
function y() {
        return j || (j = v.create(function(r) {
            e(["./identity/IdentityManager"], r)
        }).then(function(e) {
            D = e
        }))
    }
```
is loaded with JSONP by webpack using "__intern" webcontext:
http://localhost:9000/__intern/85.js

But the file is only accessible at:
http://localhost:9000/~tmp/85.js

Seems like it is more an intern issue doesn't it ?

**Comment by odoe** [comment]
I'll check with the latest version of intern and see if the issue persist. There will be a new cli release next week after 4.12 comes out, so I'm in the process of testing cli builds as well.

**Comment by Biboba** [comment]
Great ! I will follow that closely then.
Thanks for your reply

**Comment by Biboba** [comment]
FYI, I just tried with intern 4.4.3, and the issue remains

**Comment by Biboba** [comment]
Reading this [post](https://www.esri.com/arcgis-blog/products/js-api-arcgis/announcements/whats-new-in-arcgis-api-for-javascript-july-2019/), I now understand why you wanted to wait for 4.12: nativ fetch will be used so my test might be successful.
But I think the issue would still occur whenever a test will be executing ESRI JS code that will be doing a dynamic import just like "esri/request" is 4.11. 
Let's see what see what the open issue on intern will say.

**Comment by Biboba** [comment]
@jason0x43 found the trick !
In webpack test config, output.publicPath should be set to '/~tmp/'.
