### ISSUE TITLE
SceneView not work in 4.12

### ISSUE THREAD

**Issue by herrshi** [Esri/arcgis-js-cli#36]
## Description
SceneView not work in 4.12, the same code worked in 4.11

## Expected Behavior
Show map in 3D scene

## Actual Behavior
TypeError: ve is not a constructor in SceneView.js:25:3266

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project if available:

**Comment by odoe** [comment]
In the template app, 3d features are disabled by default, remove `"3d": false` from the webpack-plugin configuration in the `webpack.config.js`.
