### ISSUE TITLE
UI components

### ISSUE THREAD

**Issue by rangasatishkumar** [Esri/arcgis-js-cli#38]
Request your advise:
Which UI components (or UI library) you suggest to use along with this cli.
I would like to add UI components to widgets like DateTime picker, Calendar, Color picker, Treeview, Tabs, Accordions, etc...

Thank you.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used: 4.12.1 (jsapi)
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project if available:

**Comment by odoe** [comment]
The template app is not opinionated about UI libraries to use. There is a `calcite` option for the template app that has some UI components you may want to use.
https://esri.github.io/calcite-app-components
