### ISSUE TITLE
App Name does not refresh on re-build

### ISSUE THREAD

**Issue by gavinr** [Esri/arcgis-js-cli#4]
## Description
When running app through `npm start`, the app's name is not updated in page. It works as expected (app name changed) when running `npm run serve` though.

## Expected Behavior
Modifying the app name in `index.ts` should change the text in the header on the app

## Actual Behavior
Modifying the `appName` variable in `index.ts` does not change the text in the header on the app (still says `ARCGIS TEMPLATE APP`)

## Steps to Reproduce
1. `npm install -g @arcgis/cli`
2. `mkdir temp`
3. `cd temp`
4. `arcgis create demo .`
5. `npm start`
6. Open `src/index.ts` in a text editor, and modify the string `Template App` to anything else (Ex: `test`)
5. Notice that the webmack build happens, and the page is refreshed, but the title in the page still says `ARCGIS TEMPLATE APP`
![image](https://user-images.githubusercontent.com/209355/40364212-56e09310-5d97-11e8-9c2f-74b96d21a26e.png)

## Your Environment
* Version used: `@arcgis/cli@4.7.3`
* Browser Name and version: Chrome latest
* Operating System and version (desktop or mobile): Windows 10 Enterprise, v1607

**Comment by odoe** [comment]
Odd, it refreshed in Chrome on Win10, but not in Edge. Ii'll try on another machine, but may chalk it up to cache issues. Unless it's a webpack-dev-server issue of some sort.

**Comment by apfister** [comment]
seeing the same thing. only difference to my environment is that i'm on macOS High Sierra, 10.13.5. my chrome is version 67.0.3396.87

**Comment by odoe** [comment]
I think this might be fixed in the latest release. It was probably that service workers were being created in development mode, so what I've done in the template app is set it up so that appcache and service workers are only created in a production build. Let me know if that works @gavinr, thanks!

**Comment by jccartwright** [comment]
seems like I'm still experiencing the same issue w/ version 4.8.3

**Comment by gavinr** [comment]
I uninstalled then reinstalled, up to version `4.8.3`. I too am still seeing the issue - the title of the app for me is an old name i had before I upgraded, so it seems to be a system-wide cache thing? I'm clearing my browser cache -- are there any other places I can check (temp directories in the OS maybe?)?

**Comment by jccartwright** [comment]
My experience seems to confirm this.  I installed 4.8.3 on a machine that had not seen any earlier versions of @arcgis/cli and it worked as expected, i.e. service workers not used in development mode.

**Comment by gavinr** [comment]
Seems like this is now working fine for me in v4.13.0. Thanks!
