### ISSUE TITLE
External Config

### ISSUE THREAD

**Issue by sevenninety** [Esri/arcgis-js-cli#43]
## Description
Would it be possible to make the template configuration settings (webmap id etc.) external? Currently the config is in a typescript file and baked into the bundles. This makes it difficult to re-configure an application for different environments.

My current workaround is to add all settings to a config.json file and modify webpack.config.js to ensure it doesn't get bundled:

``
        externals: {
            appConfig: JSON.stringify(require("./config/config.json"))
        }
``

I think something like that in the template would be a useful addition.

**Comment by odoe** [comment]
Interesting idea. Let me prototype some ways of doing this, I could see a few ways to do these options.
