### ISSUE TITLE
watchUtils undefined after import

### ISSUE THREAD

**Issue by lwuersch** [Esri/arcgis-js-cli#45]
## Description
Hello there

I used this cli to create a react application template. I imported watchUtils in data/map.ts but cannot use it's methods as watchUtils is undefined after the import. Any help would be highly appreciated.

## Expected Behavior
watchUtils's methods should be accessible after loading it with 
```
import watchUtils from 'esri/core/watchUtils';
```
## Actual Behavior
Getting Error message in chrome when trying to access watchUtil's methods.
```
Uncaught (in promise) TypeError: Cannot read property 'init' of undefined
    at map.ts:21
```

## Steps to Reproduce

1. Create react application (arcgis create jsapi-react-app -t react)
2. Run npm start command 
3. Add the following code to data/map.ts:
```
import watchUtils from 'esri/core/watchUtils';

[...]

view.when(function(){
  watchUtils.init(view, "extent", function() {
    console.log("Extent changed");
  });
})
```
4. Start the application in the browser. 

## Environment

* Version used:
* Google Chrome 78.0.3904.97 
* Ubuntu 18.04

**Comment by odoe** [comment]
The `watchUtils` doesn't have a default export, so you would normally do something like this.

```ts
import { init } from 'esri/core/watchutils';
```

But if you want the entire module, you can `import * as` for the module.

```ts
import * as watchUtils from 'esri/core/watchUtils';
```

**Comment by lwuersch** [comment]
Thank you very much for your quick help! It is working now. Good to know that this works differently when using import instead of dojo's require.
