### ISSUE TITLE
v4.14.0 default template application "arcgis create jsapi-app" not working in IE11

### ISSUE THREAD

**Issue by rangasatishkumar** [Esri/arcgis-js-cli#49]
## Description

Application generated using the default template application "arcgis create jsapi-app" not working in IE11. Error logged in the browser console is "SCRIPT1010: Expected identifier".

![Error1](https://user-images.githubusercontent.com/17163418/72087553-97279300-3343-11ea-9ed0-417fb86d1901.png)

![Error2](https://user-images.githubusercontent.com/17163418/72087566-a0b0fb00-3343-11ea-98c8-5233a9acdcea.png)

## Expected Behavior

It should work in IE11

## Actual Behavior

Not working in IE11.
Working fine in Chrome.

## Steps to Reproduce

1. arcgis create jsapi-app
2. npm start
3. browse the application in IE11
4. refer to IE11 developer tools console for details of the issue

## Your Environment

* Version used: 4.14.0
* Browser Name and version: IE11
* Operating System and version (desktop or mobile): Win10 Laptop
* Link to your project if available:

**Comment by rangasatishkumar** [comment]
@odoe waiting for your valuable response please.

**Comment by COV-GIS** [comment]
Hey @rangasatishkumar. It's hard to tell what that error is without my debugging info. That being said, the api itself doesn't really support IE https://developers.arcgis.com/javascript/latest/guide/system-requirements/. And MS is only supporting IE for backward compatibility https://support.microsoft.com/en-us/help/17454/lifecycle-faq-internet-explorer.

My org was just finishing upgrading to Win10 and Edge about the time we switched to api v4.x; and the last of the Win7 and IE machines never did run the api well, if at all.

IMHO you're heading down a rabbit hole trying to get good results with 4.14 and future releases with IE.
