### ISSUE TITLE
ERROR in ./src/client/index.ts Module not found

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-js-cli#5]
Webpack cannot find "app" module.

## Description

When running `npm run build` on node v8.9.4, build fails.

## Expected Behavior

Build should work out of the box.

## Actual Behavior

Build fails.

## Possible Fix

Add uppercase to 'app' when importing module in index.ts:
import App from "./widgets/App";

## Steps to Reproduce

1. npm run build

## Context

When deploying project to Openshift, build fails but it is working locally.
I assume it is because node version is different.
On Openshift, it is node 8.9.4. On my computer: 8.11.2
After changing the case of the `import` App from "./widgets/App"`, it solved the issue.

## Your Environment

* Version used: 4.7.4
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project if available:

**Comment by Biboba** [comment]
Also, I had the same issue using jsapi-resources template:
https://github.com/Esri/jsapi-resources/tree/master/4.x/webpack/demo

**Comment by odoe** [comment]
Fixed in 4.7.5 https://github.com/Esri/arcgis-js-cli/releases/tag/4.7.5
