### ISSUE TITLE
Add view property and constructor interface to widget template?

### ISSUE THREAD

**Issue by COV-GIS** [Esri/arcgis-js-cli#52]
I almost PRed this, https://github.com/COV-GIS/arcgis-js-cli/commit/fd22488314953eab1e48d86c370c675ca92daeab, but saw new features require vetting via an issue.

Problem: Every time I scaffold a widget I have to add a constructor interface and `view` property. I assume that's common for most users (?).

Fix: Add those items to the template.

**Comment by odoe** [comment]
That would be a solid PR, thanks!
