### ISSUE TITLE
How to replace intern with jest for react apps ? 

### ISSUE THREAD

**Issue by mostafa-raafat** [Esri/arcgis-js-cli#54]
when i use the CLI to create react app by default the CLI use intern for unit test,
how can i change it from intern to jest ?

**Comment by odoe** [comment]
Look at the template for the basic and basic-cdn apps.
https://github.com/Esri/arcgis-js-cli/tree/master/templates/basic-cdn/app

I've been thinking of moving all the template apps to jest as there's more community content on it out there. It doesn't really change much. The key for the react template is `@testing-library/react`.

Thanks!

**Comment by odoe** [comment]
Fixed in [4.14.1](https://github.com/Esri/arcgis-js-cli/releases/tag/4.14.1)

**Comment by mostafa-raafat** [comment]
Thank you so much :)
