### ISSUE TITLE
npm run build react -t (eslint)

### ISSUE THREAD

**Issue by PaulPandl** [Esri/arcgis-js-cli#57]
### running 
arcgis create <app> -t react
npm install
npm run build

## Expected Behavior
Should just build

### Throws
Error: Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.js': Cannot find module 'eslint/lib/util/traverser'
Require stack:
- C:\working-2020\azure_repos\meiz\webapp\node_modules\@typescript-eslint\parser\dist\parser.js
- C:\working-2020\azure_repos\meiz\webapp\node_modules\eslint\lib\cli-engine\config-array-factory.js
- C:\working-2020\azure_repos\meiz\webapp\node_modules\eslint\lib\cli-engine\cascading-config-array-factory.js
- C:\working-2020\azure_repos\meiz\webapp\node_modules\eslint\lib\cli-engine\cli-engine.js
- C:\working-2020\azure_repos\meiz\webapp\node_modules\eslint\lib\cli-engine\index.js
- C:\working-2020\azure_repos\meiz\webapp\node_modules\eslint\lib\cli.js
- C:\working-2020\azure_repos\meiz\webapp\node_modules\eslint\bin\eslint.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\working-2020\azure_repos\meiz\webapp\node_modules\@typescript-eslint\parser\dist\parser.js:6:37)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! webapp@1.0.0 lint: `eslint --fix "src/**/*.ts?(x)"`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the webapp@1.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pau10549\AppData\Roaming\npm-cache\_logs\2020-02-13T19_24_25_850Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! webapp@1.0.0 build: `npm run lint && webpack --mode production`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the webapp@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\pau10549\AppData\Roaming\npm-cache\_logs\2020-02-13T19_24_25_896Z-debug.log

## Possible Fix
downgrade eslint: to 5.14
https://github.com/webpack-contrib/eslint-loader/issues/287

## Steps to Reproduce
1. arcgis create <name> -t react
2.npm install
3.npm run build

**Comment by odoe** [comment]
I found a fix for this. If I can manage, I'll patch current release, if not, it will be fixed in next release. Thanks!

**Comment by odoe** [comment]
Fixed in [4.14.1](https://github.com/Esri/arcgis-js-cli/releases/tag/4.14.1)
