### ISSUE TITLE
Html Webpack Plugin error

### ISSUE THREAD

**Issue by piwnk** [Esri/arcgis-js-cli#6]
After successful creation npm run start ends up with the Html Webpack Plugin error.

## Steps to Reproduce

1. Install cli
2. Create any app
3. npm run start
4.   ERROR in   Error: Child compilation failed:
  /home/piotrek/dev/esri/hello/node_modules/lodash/lodash.  js
  Cannot read property 'replace' of undefined:
  TypeError: /home/piotrek/dev/esri/hello/node_modules/lod  ash/lodash.js
  Cannot read property 'replace' of undefined

  - compiler.js:79 childCompiler.runAsChild
    [hello]/[html-webpack-plugin]/lib/compiler.js:79:16
  - Compiler.js:296 compile
    [hello]/[webpack]/lib/Compiler.js:296:11
  - Compiler.js:553 hooks.afterCompile.callAsync.err
    [hello]/[webpack]/lib/Compiler.js:553:14
  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [hello]/[tapable]/lib/Hook.js:154:20
  - Compiler.js:550 compilation.seal.err
    [hello]/[webpack]/lib/Compiler.js:550:30
  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [hello]/[tapable]/lib/Hook.js:154:20
  - Compilation.js:1295 hooks.optimizeAssets.callAsync.err    [hello]/[webpack]/lib/Compilation.js:1295:35
  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [hello]/[tapable]/lib/Hook.js:154:20
  - Compilation.js:1286 hooks.optimizeChunkAssets.callAsyn    c.err
    [hello]/[webpack]/lib/Compilation.js:1286:32
  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [hello]/[tapable]/lib/Hook.js:154:20
  - Compilation.js:1281 hooks.additionalAssets.callAsync.e    rr
    [hello]/[webpack]/lib/Compilation.js:1281:36

ERROR in chunk 0
0.dd228d767743d76848f4.js
/home/piotrek/dev/esri/hello/node_modules/arcgis-js-api/views/webgl/BufferObject.js
Cannot read property 'replace' of undefined

ERROR in chunk 1
1.b93d58426cfef4c3c98c.js
/home/piotrek/dev/esri/hello/node_modules/arcgis-js-api/views/3d/support/geometryUtils.js
Cannot read property 'replace' of undefined

ERROR in chunk 2
2.8f8a6737a979cee3510c.js
/home/piotrek/dev/esri/hello/node_modules/arcgis-js-api/views/webgl/FramebufferObject.js
Cannot read property 'replace' of undefined

ERROR in chunk 3
3.c35aae51ee2924963cd9.js
/home/piotrek/dev/esri/hello/node_modules/arcgis-js-api/views/webgl/InstanceCounter.js
Cannot read property 'replace' of undefined

ERROR in chunk 4
4.cfb4f14b056781ec34f1.js
/home/piotrek/dev/esri/hello/node_modules/arcgis-js-api/core/tsSupport/generatorHelper.js
Cannot read property 'replace' of undefined

...and so on...

## Context

No fancy things, Just running the template app. Recreated on Windows and Linux.

## Your Environment

* Version used: 4.8.3
* Browser Name and version: Chrome 69
* Operating System and version (desktop or mobile): Windows10 with node 10.11/Ubuntu 18.04 with node 8.10

**Comment by piwnk** [comment]
Fixed by downgrading webpack-html-plugin to 3.0.7 and updating webpack-cli to latest (3.1.1).

**Comment by odoe** [comment]
Sorry, most of this was fixed in the 4.8.3 of the webpack plugin (https://github.com/Esri/arcgis-webpack-plugin/releases/tag/4.8.3) but the webpack-cli needs to be updated in the template app because webpack-cli 2x breaks with latest webpack.

I'll patch this today and a new version of the cli for jsapi 4.9 will also be released this week.
