### ISSUE TITLE
Search Widget display in jsapi-react-app

### ISSUE THREAD

**Issue by lwuersch** [Esri/arcgis-js-cli#62]
Hi, 
I ran into an issue when integrating the search widget (ESRI api 4) to a React App created with this cli. I would highly appreciate help or hints in this matter:

## Description
The search widget does not look or work the way I expect: No location suggestions are offered when typing and the interface looks very much different compared to how it normally looks when only using the api 4. Other widgets (such as legend, sketch) work as expected. 

## Expected Behavior

The widget should work and look similar to [this](https://developers.arcgis.com/javascript/latest/sample-code/widgets-search-3d/index.html).

## Actual Behavior

The widget is displayed like this and offers no location suggestions as the user is typing
![image](https://user-images.githubusercontent.com/22364707/75366399-85f30100-5873-11ea-9720-e6bd74472c10.png)
![image](https://user-images.githubusercontent.com/22364707/75425237-2807fd00-58f7-11ea-9f6f-1023094e4e12.png)

## Steps to Reproduce
1. create a react application `arcgis create jsapi-react-app -t react` 
2. In map.ts, add
```
import Search from 'esri/widgets/Search';
...
export const search = new Search({
    view: view
})
view.ui.add(search, 'top-right')

```
3. Run the application with the start script

## Your Environment

* Version used: 4.14.2
* Browser Name and version: Chrome Version 80.0.3987.122
* Ubuntu 18.04.4 LTS

**Comment by odoe** [comment]
Set the sass variable to true.
https://github.com/Esri/arcgis-js-cli/blob/master/templates/react/app/src/css/main.scss#L28

```scss
// src/css/main.scss
$include_Search: true !default;
```

The sass variables have tripped a few people up, so I'll try to add it to the readme.

**Comment by lwuersch** [comment]
Thank you, that worked out nicely
