### ISSUE TITLE
BUG:  Widget implementation within ArcGIS cli jsapi project fails

### ISSUE THREAD

**Issue by powersparks** [Esri/arcgis-js-cli#63]
the command
`arcgis widget MyWidget`

## Description
There are several guides for typescript to get started, and generally these examples have aged, and require some fixing to work today.  It is not clear how to include an ArcGIS CLI widget in the ArcGIS CLI created project or how to import the same widget into the ArcGIS created project.  Additionally, there is a bug with the widget creation. 

## Expected Behavior
expected the arcgis widget template is created within the application
arcgis-js-cli/templates/basic/widget/src/widgets/WidgetName.tsx  should properly replace the Widget's Name parameter in the template.. looks like its for both the <%name>Property interface and then later in the reference to this interface.

## Actual Behavior
throws this error:
Error: The `widget` command can only be used in a `jsapi` type app scaffolded with 'arcgis-js-cli' or `exb` widgets
## Possible Fix
simple update in the documentation to show how to help with widget development, or change to the CLI.

## Steps to Reproduce
run:
arcgis create myapp
cd myapp
arcgis widget mywidget 

## Context
I'm just learning how to work with typescript to extend the arcgis javascript api widgets, so this may not be a real issue. thanks.

## Your Environment
npm version 6.13.4
vscode version 1.42.1
ArcGIS CLI broken version:4.14.2
ArcGIS CLI known good version: 4.13.0

**Comment by powersparks** [comment]
I realized after running this on my mac, that this worked at version 4.13.0

**Comment by COV-GIS** [comment]
I just updated and an having the same issue. This logic https://github.com/Esri/arcgis-js-cli/blob/master/src/lib/createWidget.js#L45-L48 always returns truthy and throws the error.

Should be `if (!pkg || pkg && (pkg.arcgis.type !== "jsapi" && pkg.arcgis.type !== "exb")) { ... }`
