### ISSUE TITLE
Cannot init vue or calcite app

### ISSUE THREAD

**Issue by dolin5** [Esri/arcgis-js-cli#64]
## Description

When initializing an app in an existing directory, the only types available are "jsapi" and "react"
## Expected Behavior

Types "vue" and "calcite" should be type options for the init command.
## Actual Behavior

path\to\my-project>arcgis init calcite
arcgis init [type]

Initialize a new application in current directory

Options:
  --version   Show version number                                      [boolean]
  --type, -t  A project template  [choices: "jsapi", "react"] [default: "jsapi"]
  -h, --help  Show help                                                [boolean]

Invalid values:
  Argument: type, Given: "calcite", Choices: "jsapi", "react"

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Version used:4.14.2
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project if available:

**Comment by odoe** [comment]
This should be fixed in [`4.14.5`](https://github.com/Esri/arcgis-js-cli/releases/tag/4.14.5)

Thanks!
