### ISSUE TITLE
4.15.0 - Compiled with warnings

### ISSUE THREAD

**Issue by rangasatishkumar** [Esri/arcgis-js-cli#69]
arcgis create jsapi-app - compiled with warnings for v4.15.0

## Description
Created an application using **arcgis create jsapi-app**. **npm start** is showing a warning as per the enclosed screenshot.

![compiled with warnings](https://user-images.githubusercontent.com/17163418/78961835-53e8e600-7b25-11ea-85de-2c627d0a5baa.png)

## Expected Behavior
There should not be any warnings

## Steps to Reproduce

1. arcgis create jsapi-app
2. npm start
3. WARNING will be recorded in the terminal
4.

## Your Environment

* Version used: 4.15.0
* Browser Name and version: Chrome 80+
* Operating System and version (desktop or mobile): Desktop, Windows 10
* Link to your project if available:

**Comment by odoe** [comment]
These warnings are expected and can be ignored. This is a webpack warning that occurs for that one file because our worker framework can load any variety of modules, so this warning happens in cases like this.

```js
require([moduleA], () => {});

// or

const moduleB = await import(moduleBvariable);
```
