### ISSUE TITLE
Cannot read properties of undefined after update to 4.9

### ISSUE THREAD

**Issue by mlewis22** [Esri/arcgis-js-cli#7]
## Summary

after updating the cli using `npm update` I am unable to run a local server or build. The interface produces

> "TypeError: Cannot read property 'properties' of undefined"

## Description
I've updated the cli to 4.9. I did this by calling `npm update`. This has updated the following modules

+ workbox-webpack-plugin@3.6.2
+ lint-staged@7.3.0
+ mini-css-extract-plugin@0.4.3
+ prettier@1.14.3
+ webpack-dev-server@3.1.9
+ webpack@4.20.2
+ @types/arcgis-js-api@4.9.0
+ intern@4.3.1
+ @arcgis/webpack-plugin@4.9.0

Runnig `npm start` causes an error (described in section below)

## Expected Behavior
Local development should initiate presenting application on browser.

## Actual Behavior
The following error occurs:

> C:\<folderspace>\node_modules\webpack-cli\bin\config-yargs.js:89
>                                 describe: optionsSchema.definitions.output.properties.path.description,
> 
> TypeError: Cannot read property 'properties' of undefined
>     at module.exports (C:\<folderspace>\node_modules\webpack-cli\bin\config-yargs.js:89:48)
>     at Object.<anonymous> (C:\<folderspace>\node_modules\webpack-dev-server\bin\webpack-dev-server.js:84:40)
>     at Module._compile (module.js:635:30)
>     at Object.Module._extensions..js (module.js:646:10)
>     at Module.load (module.js:554:32)
>     at tryModuleLoad (module.js:497:12)
>     at Function.Module._load (module.js:489:3)
>     at Function.Module.runMain (module.js:676:10)
>     at startup (bootstrap_node.js:187:16)
>     at bootstrap_node.js:608:3
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! app4x@0.0.1 serve: `webpack-dev-server --mode production --open --https --compress`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the app4x@0.0.1 serve script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\<username>\AppData\Roaming\npm-cache\_logs\2018-09-30T08_50_49_773Z-debug.log
> 

## Possible Fix
 Related to version of webpack.  
run  `npm install webpack@4.8.0`  to fix

## Steps to Reproduce

1. Create an application using 4.8 cli
2. Run `npm update`
3. Run `npm start
`

## Your Environment
* Version used: 4.9
* Browser Name and version: Chrome, Edge

**Comment by odoe** [comment]
Make sure you have updated to `webpack-cli: 3.1.1`, the 2x of webpack-cli doesn't work with some versions of webpack greater than 4.8

**Comment by mlewis22** [comment]
Thanks, i updated the cli `webpack-cli@3.1.1` and then `webpack@4.20.2` this solved the issue
