### ISSUE TITLE
Issue with typings when using ESRI JS API widget view locally

### ISSUE THREAD

**Issue by Biboba** [Esri/arcgis-js-cli#75]
## Description

When using a JS API widget view locally, there are many typings issue. Only widget properties are known but none of the inherited properties or methods are available (eg: Accessor). Do you have any idea how to fix that ? 
Thanks !

## Expected Behavior

I would expect not to have any typings error.

## Actual Behavior

Visual studio code is complaining that none of the accessor methods are available:

<img width="550" alt="Capture d’écran 2020-05-02 à 17 36 24" src="https://user-images.githubusercontent.com/11556423/80868513-7d67de00-8c9b-11ea-8c97-53dc39e57a5f.png">

## Steps to Reproduce

1. git clone a sample [repo](https://github.com/Biboba/jsapi-typings-issue) I made that is using a local version of the Editor widget 
2. Open visual studio and you should see typings error using "set" method on the editor widget in widgets.ts file.

## Your Environment

* Version used: 4.15.1
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project if available: [Project](https://github.com/Biboba/jsapi-typings-issue)

**Comment by Biboba** [comment]
Following this very nice [video](https://www.youtube.com/watch?v=E4h-5e4QnwI&list=PLaPDDLTCmy4Ys8vfmC7DbX3FHSsyosvh7&index=113) from devsummit ([repo](https://github.com/jcfranco/dev-summit-2020-customizing-widgets)), I created a subclass of the Editor widget rather than editing directly raw JS API view.
It seems to solve my initial issue ! 

So I wanted to overwrite some of the methods but now I face the issue that none of the **protected** methods are known:
<img width="581" alt="Capture d’écran 2020-05-02 à 18 26 30" src="https://user-images.githubusercontent.com/11556423/80870210-4bf41000-8ca5-11ea-88e6-a72bce5a1192.png">

In the tutorial from devsummit, they declare an interface to access **private** properties:
```
// use interface merging to access internals
interface CustomScaleRangeSlider {
  _slider: Slider;
  _minThumbNode: HTMLElement;
  _maxThumbNode: HTMLElement;
}
````

But I believe it should not be necessary for protected ones, should it ?

Thanks !

**Comment by odoe** [comment]
`protected` methods are not doc'd, so they will not be in the typings. If you need them, then you should use the same method used in that demo repo.

**Comment by Biboba** [comment]
Many thanks for your reply and your explanations !
