### ISSUE TITLE
tslint vs eslint in precommit hook

### ISSUE THREAD

**Issue by jccartwright** [Esri/arcgis-js-cli#77]
With the basic type application, the precommit hook is using tslint rather than eslint
(https://github.com/Esri/arcgis-js-cli/blob/master/templates/basic/app/package.json, line 58).  tslint was failing due to missing dependencies.

## Possible Fix

It appears that changing "tslint" to "eslint" resolves the problem but I'm uncertain if there are other ramifications to doing so.

## Steps to Reproduce

1. arcgis init
2. git add .
3. git commit -m "initial checkin"
4.

## Your Environment

* Version used:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project if available:

**Comment by odoe** [comment]
This fix is merged and be in the next release.

**Comment by odoe** [comment]
Fix was released.
