### ISSUE TITLE
4.16 - esri/geometry/projection - Uncaught (in promise) Error: both async and sync fetching of the wasm failed

### ISSUE THREAD

**Issue by rangasatishkumar** [Esri/arcgis-js-cli#82]
When used **import projection = require('esri/geometry/projection');** or **import * as projection from 'esri/geometry/projection';**, encountered below errors (recorded in console)

- _**GET http://localhost:8080/esri/geometry/support/pe-wasm.wasm 404 (Not Found)**_

- _**Uncaught (in promise) Error: both async and sync fetching of the wasm failed**_

## Description

Refer to the enclosed screenshot for full details on the error.
![projection_error](https://user-images.githubusercontent.com/17163418/87242385-ce940b00-c45e-11ea-9d63-255a610117e6.png)

Loaded _projection_ at **postInitialize** as below.
`  postInitialize() {
    projection.load();
  }`

## Expected Behavior

**esri/geometry/projection** should function with out any issue.

## Actual Behavior

Refer to the enclosed screenshot

## Possible Fix

Don't know.

> **This issue was not observed with version 4.15**

## Steps to Reproduce

1. import projection = require('esri/geometry/projection');
2. In postInitialize function, call projection.load();
3. Call projection.project somewhere in the business logic

## Context

Unable to project the geometries on client side.

## Your Environment

* Version used: 4.16
* Browser Name and version: Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)
* Operating System and version (desktop or mobile): Microsoft Windows 10 Pro (Desktop)
* Link to your project if available: N/A

**Comment by odoe** [comment]
This was an issue in the `@arcgis/webpack-plugin`, that has been fixed [here](https://github.com/Esri/arcgis-webpack-plugin/releases/tag/4.16.1).

**Comment by rangasatishkumar** [comment]
With @arcgis/webpack-plugin 4.16.1, it's working now. Thanks you @odoe
