### ISSUE TITLE
GraphicsLayer - disable update position by scale

### ISSUE THREAD

**Issue by anonanonttl** [Esri/arcgis-js-cli#84]
Hello,

I know this is not the right place for this question but I don't have an account in the esri community yet, so

Is it possible to disable updating layerView when zooming in the map? I don't want the points, lines and polygons in my graphicsLayer to redraw and their location to update according to the scale.

Thanks

**Comment by bsvensson** [comment]
> I know this is not the right place for this question but I don't have an account in the esri community yet

Hi @anonanonttl - setting up an account for the Geonet community should be easy.

As a developer, you can sign up by:
1. Go to **https://developers.arcgis.com/pricing/**
2. Under the "**What can I do for free?**" heading, click "**Start Mapping**"
