### ISSUE TITLE
Error when try to run arcgis create jsapi-react-app -t react

### ISSUE THREAD

**Issue by yobeidat** [Esri/arcgis-js-cli#89]
When try to use the CLI to create js api react app I get the below error. It seems there is an issue with communicating with ssh://git@github.com/Esri/dgrid.git 
Also I got the same error after cloning https://github.com/Esri/nearby-javascript.git repository and then run npm install.
## Description
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/Esri/dgrid.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

## Steps to Reproduce
-run the below line in the terminal
arcgis create jsapi-react-app -t react

**Comment by odoe** [comment]
You may not have ssh for github set up. You can use https by default to avoid ssh if you like.

```sh
git config --global url."https://github.com/".insteadOf git@github.com:
git config --global url."https://".insteadOf git://
```

**Comment by yobeidat** [comment]
Thank you. it worked :)
