### ISSUE TITLE
Error i.__spreadArrays is not a function when try to run arcgis create jsapi-react-app -t vue 

### ISSUE THREAD

**Issue by ringch** [Esri/arcgis-js-cli#90]
When try to use the CLI to create js api vue app I get the below error.
## Description
TypeError: i.__spreadArrays is not a function. (In 'i.__spreadArrays(n.numericTypes,["esriFieldTypeInteger","esriFieldTypeSmallInteger","esriFieldTypeSingle","esriFieldTypeDouble"])', 'i.__spreadArrays' is undefined)
（匿名函数） — fieldUtils.js:25:7597
./node_modules/arcgis-js-api/layers/support/fieldUtils.js — fieldUtils.js:25:11031
__webpack_require__ — bootstrap:63
./node_modules/arcgis-js-api/PopupTemplate.js — PopupTemplate.js:25:240
__webpack_require__ — bootstrap:63
./node_modules/arcgis-js-api/Graphic.js — Graphic.js:25
__webpack_require__ — bootstrap:63
./node_modules/arcgis-js-api/views/MapView.js — MapView.js:25
__webpack_require__ — bootstrap:63
./src/data/map.ts — 183.5db52b5f2035f0552980.js:22:128
__webpack_require__ — bootstrap:63
（匿名函数） — bootstrap:161
[native code]
promiseReactionJob

**Comment by Biboba** [comment]
You need to update your tslib package to 1.10.0

**Comment by odoe** [comment]
Thanks for the PR, much appreciated!
