### ISSUE TITLE
Cannot find module 'core-js/modules/es.function.name.js'

### ISSUE THREAD

**Issue by jccartwright** [Esri/arcgis-js-cli#95]
fresh install of version 4.18. running command with --version or --help produces error and stacktrace

## Description

running command with "arcgis --version"

## Expected Behavior

report version number

## Actual Behavior

error and stack trace

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'core-js/modules/es.function.name.js'
Require stack:
- /Users/jcc/.nvm/versions/node/v12.20.0/lib/node_modules/@arcgis/cli/dist/commands/create.js
- /Users/jcc/.nvm/versions/node/v12.20.0/lib/node_modules/@arcgis/cli/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/jcc/.nvm/versions/node/v12.20.0/lib/node_modules/@arcgis/cli/dist/commands/create.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/jcc/.nvm/versions/node/v12.20.0/lib/node_modules/@arcgis/cli/dist/commands/create.js',
    '/Users/jcc/.nvm/versions/node/v12.20.0/lib/node_modules/@arcgis/cli/dist/index.js'
  ]
}

## Steps to Reproduce

1. npm install -g @arcgis/cli
2. arcgis --version
3.
4.

## Context

unable to do anything with the CLI at this point

## Your Environment

* Version used: arcgis-js-cli v4.18, node version v12.20.0 and v14.15.3
* Browser Name and version: N/A
* Operating System and version (desktop or mobile): Mac 10.15.6
* Link to your project if available:

**Comment by odoe** [comment]
odd, let me debug a bit. it worked with npm link, but might need to pack it first then try

**Comment by odoe** [comment]
This should be fixed in `4.18.1`

**Comment by jccartwright** [comment]
Thanks Rene, that does seem to address my original issue and I really appreciate the fast response!

I'm noticing now however that I'm unable to successfully generate a JSAPI widget, getting the error:

ERROR in ./src/widgets/MyWidget.tsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/jcc/projects/arcgis-widget-test/src/widgets/MyWidget.tsx: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (20:1):

Adding ' "experimentalDecorators": true' to the tsconfig compilerOptions doesn't seem to help.  Shall I open a separate issue on this?

**Comment by odoe** [comment]
Please do, I'll need to update the Widget output and possibly the tsconfig for the templates. Thanks!
